platform :ios, '16.0'

target 'HabitTracker' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HabitTracker

  target 'HabitTrackerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HabitTrackerUITests' do
    # Pods for testing
  end

end
