platform :ios, '16.0'

target 'HabitTracker' do
  use_frameworks!
  
  # Lottie pod'u ekleyelim
  pod 'lottie-ios'

  # Pods for HabitTracker

  target 'HabitTrackerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HabitTrackerUITests' do
    # Pods for testing
  end

end
